import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Layout from '@/components/layout/Layout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { registerAsSeller } from '@/services/sellerService';
import { uploadSellerDocument } from '@/lib/firebase'; // Ensure this matches your firebase utility file path
import {
  Shield,
  CheckCircle,
  User,
  Phone,
  ArrowRight,
  Building2,
  Mail,
  FileText,
  UploadCloud
} from 'lucide-react';

const SellerRegisterPage: React.FC = () => {
  const { user, isAuthenticated } = useAuth();
  const { toast } = useToast();
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    name: user?.name || '',
    email: user?.email || '',
    phone: user?.phone || '',
    id_proof_type: 'aadhar', // Default selection
  });

  const [idFile, setIdFile] = useState<File | null>(null);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    if (formErrors[name]) {
      setFormErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setIdFile(e.target.files[0]);
      if (formErrors.id_file) {
        setFormErrors(prev => ({ ...prev, id_file: '' }));
      }
    }
  };

  const validateForm = (): boolean => {
    const errors: Record<string, string> = {};

    if (!formData.name.trim()) errors.name = 'Name is required';
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      errors.email = 'Enter a valid email address';
    }

    if (!formData.phone.trim()) {
      errors.phone = 'Phone number is required';
    } else if (!/^[+]?[\d\s-]{10,}$/.test(formData.phone)) {
      errors.phone = 'Enter a valid phone number';
    }

    if (!idFile) {
      errors.id_file = 'Please upload an ID proof document';
    }

    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!isAuthenticated || !user) {
      navigate('/auth?redirect=seller/register');
      return;
    }

    if (!validateForm() || !idFile) return;

    setIsSubmitting(true);

    try {
      // 1. Upload the document to Firebase Storage
      // We use the uploadSellerDocument function from your firebase.ts
      // Inside handleSubmit in SellerRegisterPage.tsx
const idProofUrl = await uploadSellerDocument(
  idFile,
  formData.id_proof_type, // Only pass file and type now
  (progressInfo) => setUploadProgress(Math.round(progressInfo.progress))
);
      // 2. Submit the registration data to your backend
      const response = await registerAsSeller({
        user_id: user.id,
        name: formData.name,
        email: formData.email,
        phone: formData.phone,
        id_proof_type: formData.id_proof_type,
        id_proof_url: idProofUrl, // Passing the URL generated by Firebase
      });

      if (!response.success) {
        throw new Error(response.error || 'Registration failed');
      }

      toast({
        title: "Application Submitted",
        description: "Your seller application is under review.",
      });

      navigate('/seller');
    } catch (error: any) {
      toast({
        title: "Registration Failed",
        description: error.message || 'Please try again later.',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
      setUploadProgress(0);
    }
  };

  // ... (Keep existing isAuthenticated and user.role === 'seller' checks)

  return (
    <Layout>
      <div className="container py-16">
        <div className="max-w-2xl mx-auto">
          {/* Header & Benefits UI stays the same... */}
          
          <Card>
            <CardHeader>
              <CardTitle>Seller Registration</CardTitle>
              <CardDescription>
                Fill in your details and upload ID proof for verification.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-6">

                {/* Name, Email, Phone fields... */}
                <div className="space-y-2">
                  <Label className="flex items-center gap-1">
                    <User className="h-4 w-4" /> Full Name *
                  </Label>
                  <Input name="name" value={formData.name} onChange={handleInputChange} />
                </div>

                <div className="space-y-2">
                  <Label className="flex items-center gap-1">
                    <Mail className="h-4 w-4" /> Email *
                  </Label>
                  <Input name="email" type="email" value={formData.email} onChange={handleInputChange} />
                </div>

                <div className="space-y-2">
                  <Label className="flex items-center gap-1">
                    <Phone className="h-4 w-4" /> Phone Number *
                  </Label>
                  <Input name="phone" value={formData.phone} onChange={handleInputChange} />
                </div>

                {/* NEW: ID Proof Type */}
                <div className="space-y-2">
                  <Label className="flex items-center gap-1">
                    <FileText className="h-4 w-4" /> ID Proof Type *
                  </Label>
                  <select
                    name="id_proof_type"
                    value={formData.id_proof_type}
                    onChange={handleInputChange}
                    className="w-full h-10 px-3 py-2 bg-background border border-input rounded-md text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring"
                  >
                    <option value="aadhar">Aadhar Card</option>
                    <option value="pan">PAN Card</option>
                    <option value="passport">Passport</option>
                    <option value="driving_license">Driving License</option>
                  </select>
                </div>

                {/* NEW: ID Proof File Upload */}
                <div className="space-y-2">
                  <Label className="flex items-center gap-1">
                    <UploadCloud className="h-4 w-4" /> Upload ID Proof *
                  </Label>
                  <div className={`border-2 border-dashed rounded-lg p-4 text-center ${formErrors.id_file ? 'border-destructive' : 'border-muted'}`}>
                    <Input
                      type="file"
                      accept="image/*,.pdf"
                      onChange={handleFileChange}
                      className="cursor-pointer"
                    />
                    <p className="text-xs text-muted-foreground mt-2">
                      Accepted formats: JPG, PNG, PDF (Max 5MB)
                    </p>
                  </div>
                  {formErrors.id_file && <p className="text-xs text-destructive">{formErrors.id_file}</p>}
                </div>

                {/* Upload Progress Bar */}
                {isSubmitting && uploadProgress > 0 && (
                  <div className="space-y-1">
                    <div className="flex justify-between text-xs">
                      <span>Uploading document...</span>
                      <span>{uploadProgress}%</span>
                    </div>
                    <div className="w-full bg-muted rounded-full h-2">
                      <div 
                        className="bg-primary h-2 rounded-full transition-all duration-300" 
                        style={{ width: `${uploadProgress}%` }}
                      />
                    </div>
                  </div>
                )}

                <Button type="submit" className="w-full gap-2" disabled={isSubmitting}>
                  {isSubmitting ? "Processing..." : <>Submit for Verification<ArrowRight className="h-4 w-4" /></>}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </Layout>
  );
};

export default SellerRegisterPage;